### ISSUE TITLE
GTK4 support

### ISSUE THREAD

**Issue by taozuhong** [wszqkzqk/GTK-MSYS2-example-packer#1]
GTK4 支持时必须的呀，整起来不？

**Comment by wszqkzqk** [comment]
GTK4的主题文件这些和GTK3一样吗

**Comment by wszqkzqk** [comment]
假如还是这几个目录也许一行就能搞定

**Comment by wszqkzqk** [comment]
我发现GTK4不需要额外打包主题文件就能运行，但是在Windows环境下都没有应用GNOME的主题

**Comment by taozuhong** [comment]
GTK4 默认没有主题。

**Comment by wszqkzqk** [comment]
> GTK4 默认没有主题。

那么是不是只需要复制依赖和gdk-pixbuf-2.0就行了

现在哪里有GTK4/Vala的文档啊，感觉没什么迁移学习途径

**Comment by taozuhong** [comment]
https://www.datatable.online/zh/blog/002-how-to-deploy-gtk-app-on-windows.html
GTK3成功了，GTK4 基本上很容易，用新库并找到它的依赖即可。

**Comment by wszqkzqk** [comment]
> https://www.datatable.online/zh/blog/002-how-to-deploy-gtk-app-on-windows.html GTK3成功了，GTK4 基本上很容易，用新库并找到它的依赖即可。

我这里只打包相关lib就能运行了
